apiVersion: v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels: # labels for pods
      app: mongo
  template: # template for pods
    metadata:
      labels: # labels for pods shared with deployment
        app: mongo # key-value pairs
    spec:
      continaers: # which containers to run and port to expose in each container
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          # value or valueFrom
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
      # volumeMounts:
      # - name: mongo-storage
      #   mountPath: /data/db
---
# service
apiVersion: v1
kind: Service
metadata:
  name: mongo-service # name of service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017